# Generated by Django 6.0.5 on 2026-05-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leage',
            new_name='League',
        ),
        migrations.RenameField(
            model_name='footballclub',
            old_name='leage',
            new_name='league',
        ),
    ]
